name: stitch_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - opencv
  - pip
  - pip:
      - cupy-cuda12x
      - fastrlock
      - progressbar2
