name: stitch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - opencv=4.5.*
  - numpy=1.19.*
  - matplotlib=3.3.*
  - pillow=8.0.*
  - progressbar2=4.0.*
  - pip
  - pip:
    - opencv-python==4.5.*
